### PR TITLE
FIX IMPORTING MODULES, ADDS CREATE CONTROLLER AND CREATE MVCS

### PR DESCRIPTION
**Pull request by iflare3g**
Adds create_controller
Adds tests for create controller
Adds tests for mvcs
Fix importing modules

### CODE REVIEW

**Comment by iflare3g** [comment]
NOTE 

I forgot to add to gitignore files generated by tests, sorry for that! 

As soon as I can, I will work on create service!

**Review by marcosstefani — APPROVED** [review]
Congrats guy!  👍

**Comment by marcosstefani** [comment]
https://github.com/marcosstefani/flute/issues/3

**Comment by marcosstefani** [comment]
https://github.com/marcosstefani/flute/issues/2

**Comment by iflare3g** [comment]
Thanks so much!

**Pull request merged**
